### ISSUE TITLE
Determine the right consistency level for DocDb 

### ISSUE THREAD

**Issue by jillcary** [Azure/pcs-storage-adapter-dotnet#27]
# Type of issue

- [] Bug
- [ ] New feature
- [x ] Improvement

# Description
We need to look at whether consistency level of Session will work for us as I suspect it will be cheaper and scale better.

Local deployment on windows returns the following error message:

# Steps to reproduce

1. run pcs-storage-adapter from master branch
2. make a request with http://localhost:9022/v1/collections/rules/values via postman with body:
{ "Data":" " }

# Expected behavior

Return 200 OK and store data.

# Current behavior

Returns 500 with: ConsistencyLevel Strong specified in the request is invalid when service is configured with consistency level Session. Ensure the request consistency level is not stronger than the service consistency level.

# Possible solution

Change to ConsistencyLevel.Session in DocumentDbKeyValueContainer.cs
```
        private RequestOptions GetDocDbOptions()
        {
            return new RequestOptions
            {
                OfferThroughput = this.docDbRUs,
                ConsistencyLevel = ConsistencyLevel.Session
            };
        }
```
# Context and Environment
* Operating System: Windows

**Comment by ppathan** [comment]
Tracked in TFS

**Comment by jillcary** [comment]
Session level consistency should meet our needs. It provides monotonic reads and writes for a session and it would have lower latency and the cost of a read operation in RUs is less than strong.

The downside is that outside of a particular session, reads and writes are subject to eventual consistency. This would mean separate users could see different data. For example there are two Operators monitoring a solution. One sees an alarm as open and other operator sees the alarm as acknowledged.
