### ISSUE TITLE
Add authorization logic

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-storage-adapter-dotnet#35]
# Type of issue

- [ ] Bug
- [x] New feature
- [ ] Improvement

# Description
1. Add the authorization logic used by the other microservices, so the projects are more consistent.
2. Also revisit the configuration files to be in sync with other projects
3. Same for scripts, sync with other projects

**Comment by sushilraje** [comment]
Issue in the new repo https://github.com/Azure/remote-monitoring-services-dotnet/issues/97.
