### ISSUE TITLE
ETags should be random (?)

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-storage-adapter-dotnet#38]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

ETags returned by the storage adapter seem suspiciously not random, as if we have custom code to generate the GUIDs, for example:

1. 5d0189fb-0000-0000-0000-59e3d5c60000
2. 5d018afb-0000-0000-0000-59e3d5d50000
3. 5d018bfb-0000-0000-0000-59e3d65f0000

If the intent is to have growing numbers, e.g. like versions, we should document why we have this feature, in which scenarios it is used, how it works, have tests (if not there already)

**Comment by xzsheng** [comment]
The ETag comes from Cosmos DB document itself. There is no code to generate it in our own code.
