### ISSUE TITLE
PCS Storage adapter documentation enhancements: PM feedback

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-storage-adapter-dotnet#39]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [X] Enhancement

# Description 
Improve documentation according to One Note feedback (Github documentation gaps)

**Comment by sushilraje** [comment]
Corresponding issue in the new repo https://github.com/Azure/remote-monitoring-services-dotnet/issues/96.
