### ISSUE TITLE
Error Using Docker Toolbox -> In file '.\docker-compose.yml', service must be a mapping, not a NoneType.

### ISSUE THREAD

**Issue by scout208** [Azure/pcs-storage-adapter-dotnet#41]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
When trying to run `docker-compose up` from the docker folder in scripts, the following error is returned:

```ERROR:` In file '.\docker-compose.yml', service must be a mapping, not a NoneType.```

# Steps to reproduce 

Simply the steps in the README under the heading, **Quickstart - Running the service with Docker** (https://github.com/Azure/device-simulation-dotnet/blob/master/README.md#quickstart---running-the-service-with-docker)

# Expected behavior 
No error.

# Current behavior 
Error prevents anything from happening. Also docker-compose.yml file looks very sparse.

# Known workarounds 
None.

# Possible solution 
???

# Context and Environment
* Operating System: Docker Toolbox on Windows 10 Home 16299.19
* GitHub branch: master
* .NET Runtime: ???
* Docker version:
```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:00:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by sushilraje** [comment]
This issue has been migrated to the new repo https://github.com/Azure/remote-monitoring-services-dotnet/issues/95.
