### ISSUE TITLE
Update readme to set default consistency to Strong for Cosmos DB

### ISSUE THREAD

**Issue by joelhulen** [Azure/pcs-storage-adapter-dotnet#43]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

When you provision a new Cosmos DB instance using the SQL API, the default consistency level is set to SESSION. This causes the DocumentDbKeyValueContainer.CreateDatabaseIfNotExistsAsync method to throw the following error: `ConsistencyLevel Strong specified in the request is invalid when service is configured with consistency level Session. Ensure the request consistency level is not stronger than the service consistency level.`

This is because the RequestOptions in this class sets the consistency level to Strong.

# Possible solution 

Update the readme in the following way:

1. Change the "DocumentDB" API to "SQL" (this is the new name for the API)
2. Add a step to change the Default consistency level to STRONG

**Comment by dluc** [comment]
@Azure/iot-solutions-team please loop me in the design conversation before changing the consistency settings

**Comment by jillcary** [comment]
This is also related to https://github.com/Azure/pcs-storage-adapter-dotnet/issues/27

**Comment by dluc** [comment]
@ppathan this issue is still open. We should change the code not to depend on the default setting if possible, so there wouldn't be need to document and one could reuse an existing DocDb instance, regardless of its settings.

**Comment by sushilraje** [comment]
This issue has been migrated to the new repo https://github.com/Azure/remote-monitoring-services-dotnet/issues/94
